// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf3ftNRlKjUkSixMKyfVa0hPKiTx0r3SE',
    appId: '1:49069215161:web:3a8a55680eb9f4e328ba68',
    messagingSenderId: '49069215161',
    projectId: 'bikestore-735a3',
    authDomain: 'bikestore-735a3.firebaseapp.com',
    storageBucket: 'bikestore-735a3.appspot.com',
    measurementId: 'G-W0TGXBMBYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmc1EGZxeCP9aGTqEnIgDP3igp2rnV4R8',
    appId: '1:49069215161:android:90075d9abd8ed74a28ba68',
    messagingSenderId: '49069215161',
    projectId: 'bikestore-735a3',
    storageBucket: 'bikestore-735a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB0HTkJXX7Sk3J6PFSUW1dzt7QfIadqBg',
    appId: '1:49069215161:ios:d60166034f5270b428ba68',
    messagingSenderId: '49069215161',
    projectId: 'bikestore-735a3',
    storageBucket: 'bikestore-735a3.appspot.com',
    iosBundleId: 'com.example.scr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB0HTkJXX7Sk3J6PFSUW1dzt7QfIadqBg',
    appId: '1:49069215161:ios:5ad0bd7fc7e4f5b228ba68',
    messagingSenderId: '49069215161',
    projectId: 'bikestore-735a3',
    storageBucket: 'bikestore-735a3.appspot.com',
    iosBundleId: 'com.example.scr.RunnerTests',
  );
}
